name: Build youtube video downloaderi

on:
  schedule:
    # Runs at 6:30 AM EAT (3:30 AM UTC)
    - cron: '30 3 * * *'

# Runs at 6:32 AM EAT (3:32 AM UTC)
    - cron: '32 3 * * *'

# Runs at 6:34 AM EAT (3:34 AM UTC)
    - cron: '34 3 * * *'

# Runs at 6:36 AM EAT (3:36 AM UTC)
    - cron: '36 3 * * *'

# Runs at 6:38 AM EAT (3:38 AM UTC)
    - cron: '38 3 * * *'

# Runs at 6:40 AM EAT (3:40 AM UTC)
    - cron: '40 3 * * *'
  push:
    branches: ['dl']

jobs:
  Download-vid:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install ffmpeg
      - name: Install ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      # Uncomment this line if you need to make a script executable
      # - run: chmod +x YoutubeVideoDownloader.sh

      # Sample script execution and GitHub release creation
      - name: videos
        run: |
          cd test
          bash foo.sh  # Make sure foo.sh exists in the 'test' directory and is executable
          gh release create "${{ github.run_number }}.0.0" vid/*.jpg
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
        shell: bash

