name: Build youtube video downloaderi

on:
  schedule:
    #Runs at 6:00 AM EAT (3:00 AM UTC)
    - cron: '0 3 * * *'

# Runs at 6:05 AM EAT (3:05 AM UTC)
    - cron: '5 3 * * *'

# Runs at 6:10 AM EAT (3:10 AM UTC)
    - cron: '10 3 * * *'

# Runs at 6:15 AM EAT (3:15 AM UTC)
    - cron: '15 3 * * *'

# Runs at 6:20 AM EAT (3:20 AM UTC)
    - cron: '20 3 * * *'

# Runs at 6:25 AM EAT (3:25 AM UTC)
    - cron: '25 3 * * *'

# Runs at 6:30 AM EAT (3:30 AM UTC)
    - cron: '30 3 * * *'

# Runs at 6:35 AM EAT (3:35 AM UTC)
    - cron: '35 3 * * *'

# Runs at 6:40 AM EAT (3:40 AM UTC)
    - cron: '40 3 * * *'

# Runs at 6:45 AM EAT (3:45 AM UTC)
    - cron: '45 3 * * *'

# Runs at 6:50 AM EAT (3:50 AM UTC)
    - cron: '50 3 * * *'

# Runs at 6:55 AM EAT (3:55 AM UTC)
    - cron: '55 3 * * *'

# Runs at 7:00 AM EAT (4:00 AM UTC)
    - cron: '0 4 * * *'

# Runs at 7:05 AM EAT (4:05 AM UTC)
    - cron: '5 4 * * *'

# Runs at 7:10 AM EAT (4:10 AM UTC)
    - cron: '10 4 * * *'

# Runs at 7:15 AM EAT (4:15 AM UTC)
    - cron: '15 4 * * *'

# Runs at 7:20 AM EAT (4:20 AM UTC)
    - cron: '20 4 * * *'

# Runs at 7:25 AM EAT (4:25 AM UTC)
    - cron: '25 4 * * *'

# Runs at 7:30 AM EAT (4:30 AM UTC)
    - cron: '30 4 * * *'

# Runs at 7:35 AM EAT (4:35 AM UTC)
    - cron: '35 4 * * *'

# Runs at 7:40 AM EAT (4:40 AM UTC)
    - cron: '40 4 * * *'

# Runs at 7:45 AM EAT (4:45 AM UTC)
    - cron: '45 4 * * *'

# Runs at 7:50 AM EAT (4:50 AM UTC)
    - cron: '50 4 * * *'

# Runs at 7:55 AM EAT (4:55 AM UTC)
    - cron: '55 4 * * *'

# Runs at 8:00 AM EAT (5:00 AM UTC)
    - cron: '0 5 * * *'

# Runs at 8:05 AM EAT (5:05 AM UTC)
    - cron: '5 5 * * *'

# Runs at 8:10 AM EAT (5:10 AM UTC)
    - cron: '10 5 * * *'

# Runs at 8:15 AM EAT (5:15 AM UTC)
    - cron: '15 5 * * *'

# Runs at 8:20 AM EAT (5:20 AM UTC)
    - cron: '20 5 * * *'

# Runs at 8:25 AM EAT (5:25 AM UTC)
    - cron: '25 5 * * *'

# Runs at 8:30 AM EAT (5:30 AM UTC)
    - cron: '30 5 * * *'

# Runs at 8:35 AM EAT (5:35 AM UTC)
    - cron: '35 5 * * *'

# Runs at 8:40 AM EAT (5:40 AM UTC)
    - cron: '40 5 * * *'

# Runs at 8:45 AM EAT (5:45 AM UTC)
    - cron: '45 5 * * *'

# Runs at 8:50 AM EAT (5:50 AM UTC)
    - cron: '50 5 * * *'

# Runs at 8:55 AM EAT (5:55 AM UTC)
    - cron: '55 5 * * *'

# Runs at 9:00 AM EAT (6:00 AM UTC)
    - cron: '0 6 * * *'

# Runs at 9:05 AM EAT (6:05 AM UTC)
    - cron: '5 6 * * *'

# Runs at 9:10 AM EAT (6:10 AM UTC)
    - cron: '10 6 * * *'

# Runs at 9:15 AM EAT (6:15 AM UTC)
    - cron: '15 6 * * *'

# Runs at 9:20 AM EAT (6:20 AM UTC)
    - cron: '20 6 * * *'

# Runs at 9:25 AM EAT (6:25 AM UTC)
    - cron: '25 6 * * *'

# Runs at 9:30 AM EAT (6:30 AM UTC)
    - cron: '30 6 * * *'

# Runs at 9:35 AM EAT (6:35 AM UTC)
    - cron: '35 6 * * *'

# Runs at 9:40 AM EAT (6:40 AM UTC)
    - cron: '40 6 * * *'

# Runs at 9:45 AM EAT (6:45 AM UTC)
    - cron: '45 6 * * *'

# Runs at 9:50 AM EAT (6:50 AM UTC)
    - cron: '50 6 * * *'

# Runs at 9:55 AM EAT (6:55 AM UTC)
    - cron: '55 6 * * *'

# Runs at 10:00 AM EAT (7:00 AM UTC)
    - cron: '0 7 * * *'

# Runs at 10:05 AM EAT (7:05 AM UTC)
    - cron: '5 7 * * *'

# Runs at 10:10 AM EAT (7:10 AM UTC)
    - cron: '10 7 * * *'

# Runs at 10:15 AM EAT (7:15 AM UTC)
    - cron: '15 7 * * *'

# Runs at 10:20 AM EAT (7:20 AM UTC)
    - cron: '20 7 * * *'

# Runs at 10:25 AM EAT (7:25 AM UTC)
    - cron: '25 7 * * *'

# Runs at 10:30 AM EAT (7:30 AM UTC)
    - cron: '30 7 * * *'

# Runs at 10:35 AM EAT (7:35 AM UTC)
    - cron: '35 7 * * *'

# Runs at 10:40 AM EAT (7:40 AM UTC)
    - cron: '40 7 * * *'

# Runs at 10:45 AM EAT (7:45 AM UTC)
    - cron: '45 7 * * *'

# Runs at 10:50 AM EAT (7:50 AM UTC)
    - cron: '50 7 * * *'

# Runs at 10:55 AM EAT (7:55 AM UTC)
    - cron: '55 7 * * *'

# Runs at 11:00 AM EAT (8:00 AM UTC)
    - cron: '0 8 * * *'

# Runs at 11:05 AM EAT (8:05 AM UTC)
    - cron: '5 8 * * *'

# Runs at 11:10 AM EAT (8:10 AM UTC)
    - cron: '10 8 * * *'

# Runs at 11:15 AM EAT (8:15 AM UTC)
    - cron: '15 8 * * *'

# Runs at 11:20 AM EAT (8:20 AM UTC)
    - cron: '20 8 * * *'

# Runs at 11:25 AM EAT (8:25 AM UTC)
    - cron: '25 8 * * *'

# Runs at 11:30 AM EAT (8:30 AM UTC)
    - cron: '30 8 * * *'

# Runs at 11:35 AM EAT (8:35 AM UTC)
    - cron: '35 8 * * *'

# Runs at 11:40 AM EAT (8:40 AM UTC)
    - cron: '40 8 * * *'

# Runs at 11:45 AM EAT (8:45 AM UTC)
    - cron: '45 8 * * *'

# Runs at 11:50 AM EAT (8:50 AM UTC)
    - cron: '50 8 * * *'

# Runs at 11:55 AM EAT (8:55 AM UTC)
    - cron: '55 8 * * *'

# Runs at 12:00 PM EAT (9:00 AM UTC)
    - cron: '0 9 * * *'

# Runs at 12:05 PM EAT (9:05 AM UTC)
    - cron: '5 9 * * *'

# Runs at 12:10 PM EAT (9:10 AM UTC)
    - cron: '10 9 * * *'

# Runs at 12:15 PM EAT (9:15 AM UTC)
    - cron: '15 9 * * *'

# Runs at 12:20 PM EAT (9:20 AM UTC)
    - cron: '20 9 * * *'

# Runs at 12:25 PM EAT (9:25 AM UTC)
    - cron: '25 9 * * *'

# Runs at 12:30 PM EAT (9:30 AM UTC)
    - cron: '30 9 * * *'

# Runs at 12:35 PM EAT (9:35 AM UTC)
    - cron: '35 9 * * *'

# Runs at 12:40 PM EAT (9:40 AM UTC)
    - cron: '40 9 * * *'

# Runs at 12:45 PM EAT (9:45 AM UTC)
    - cron: '45 9 * * *'

# Runs at 12:50 PM EAT (9:50 AM UTC)
    - cron: '50 9 * * *'

# Runs at 12:55 PM EAT (9:55 AM UTC)
    - cron: '55 9 * * *'

# Runs at 1:00 PM EAT (10:00 AM UTC)
    - cron: '0 10 * * *'

# Runs at 1:05 PM EAT (10:05 AM UTC)
    - cron: '5 10 * * *'

# Runs at 1:10 PM EAT (10:10 AM UTC)
    - cron: '10 10 * * *'

# Runs at 1:15 PM EAT (10:15 AM UTC)
    - cron: '15 10 * * *'

# Runs at 1:20 PM EAT (10:20 AM UTC)
    - cron: '20 10 * * *'

# Runs at 1:25 PM EAT (10:25 AM UTC)
    - cron: '25 10 * * *'

# Runs at 1:30 PM EAT (10:30 AM UTC)
    - cron: '30 10 * * *'

# Runs at 1:35 PM EAT (10:35 AM UTC)
    - cron: '35 10 * * *'

# Runs at 1:40 PM EAT (10:40 AM UTC)
    - cron: '40 10 * * *'

# Runs at 1:45 PM EAT (10:45 AM UTC)
    - cron: '45 10 * * *'

# Runs at 1:50 PM EAT (10:50 AM UTC)
    - cron: '50 10 * * *'

# Runs at 1:55 PM EAT (10:55 AM UTC)
    - cron: '55 10 * * *'

# Runs at 2:00 PM EAT (11:00 AM UTC)
    - cron: '0 11 * * *'

# Runs at 2:05 PM EAT (11:05 AM UTC)
    - cron: '5 11 * * *'

# Runs at 2:10 PM EAT (11:10 AM UTC)
    - cron: '10 11 * * *'

# Runs at 2:15 PM EAT (11:15 AM UTC)
    - cron: '15 11 * * *'

# Runs at 2:20 PM EAT (11:20 AM UTC)
    - cron: '20 11 * * *'

# Runs at 2:25 PM EAT (11:25 AM UTC)
    - cron: '25 11 * * *'

# Runs at 2:30 PM EAT (11:30 AM UTC)
    - cron: '30 11 * * *'

# Runs at 2:35 PM EAT (11:35 AM UTC)
    - cron: '35 11 * * *'

# Runs at 2:40 PM EAT (11:40 AM UTC)
    - cron: '40 11 * * *'

# Runs at 2:45 PM EAT (11:45 AM UTC)
    - cron: '45 11 * * *'

# Runs at 2:50 PM EAT (11:50 AM UTC)
    - cron: '50 11 * * *'

# Runs at 2:55 PM EAT (11:55 AM UTC)
    - cron: '55 11 * * *'

# Runs at 3:00 PM EAT (12:00 PM UTC)
    - cron: '0 12 * * *'

# Runs at 3:05 PM EAT (12:05 PM UTC)
    - cron: '5 12 * * *'

# Runs at 3:10 PM EAT (12:10 PM UTC)
    - cron: '10 12 * * *'

# Runs at 3:15 PM EAT (12:15 PM UTC)
    - cron: '15 12 * * *'

# Runs at 3:20 PM EAT (12:20 PM UTC)
    - cron: '20 12 * * *'

# Runs at 3:25 PM EAT (12:25 PM UTC)
    - cron: '25 12 * * *'

# Runs at 3:30 PM EAT (12:30 PM UTC)
    - cron: '30 12 * * *'

# Runs at 3:35 PM EAT (12:35 PM UTC)
    - cron: '35 12 * * *'

# Runs at 3:40 PM EAT (12:40 PM UTC)
    - cron: '40 12 * * *'

# Runs at 3:45 PM EAT (12:45 PM UTC)
    - cron: '45 12 * * *'

# Runs at 3:50 PM EAT (12:50 PM UTC)
    - cron: '50 12 * * *'

# Runs at 3:55 PM EAT (12:55 PM UTC)
    - cron: '55 12 * * *'

# Runs at 4:00 PM EAT (1:00 PM UTC)
    - cron: '0 13 * * *'

# Runs at 4:05 PM EAT (1:05 PM UTC)
    - cron: '5 13 * * *'

# Runs at 4:10 PM EAT (1:10 PM UTC)
    - cron: '10 13 * * *'

# Runs at 4:15 PM EAT (1:15 PM UTC)
    - cron: '15 13 * * *'

# Runs at 4:20 PM EAT (1:20 PM UTC)
    - cron: '20 13 * * *'

# Runs at 4:25 PM EAT (1:25 PM UTC)
    - cron: '25 13 * * *'

# Runs at 4:30 PM EAT (1:30 PM UTC)
    - cron: '30 13 * * *'

# Runs at 4:35 PM EAT (1:35 PM UTC)
    - cron: '35 13 * * *'

# Runs at 4:40 PM EAT (1:40 PM UTC)
    - cron: '40 13 * * *'

# Runs at 4:45 PM EAT (1:45 PM UTC)
    - cron: '45 13 * * *'

# Runs at 4:50 PM EAT (1:50 PM UTC)
    - cron: '50 13 * * *'

# Runs at 4:55 PM EAT (1:55 PM UTC)
    - cron: '55 13 * * *'

# Runs at 5:00 PM EAT (2:00 PM UTC)
    - cron: '0 14 * * *'

# Runs at 5:05 PM EAT (2:05 PM UTC)
    - cron: '5 14 * * *'

# Runs at 5:10 PM EAT (2:10 PM UTC)
    - cron: '10 14 * * *'

# Runs at 5:15 PM EAT (2:15 PM UTC)
    - cron: '15 14 * * *'

# Runs at 5:20 PM EAT (2:20 PM UTC)
    - cron: '20 14 * * *'

# Runs at 5:25 PM EAT (2:25 PM UTC)
    - cron: '25 14 * * *'

# Runs at 5:30 PM EAT (2:30 PM UTC)
    - cron: '30 14 * * *'

# Runs at 5:35 PM EAT (2:35 PM UTC)
    - cron: '35 14 * * *'

# Runs at 5:40 PM EAT (2:40 PM UTC)
    - cron: '40 14 * * *'

# Runs at 5:45 PM EAT (2:45 PM UTC)
    - cron: '45 14 * * *'

# Runs at 5:50 PM EAT (2:50 PM UTC)
    - cron: '50 14 * * *'

# Runs at 5:55 PM EAT (2:55 PM UTC)
    - cron: '55 14 * * *'

# Runs at 6:00 PM EAT (3:00 PM UTC)
    - cron: '0 15 * * *'
  push:
    branches: ['dl']

jobs:
  Download-vid:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install ffmpeg
      - name: Install ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      # Uncomment this line if you need to make a script executable
      # - run: chmod +x YoutubeVideoDownloader.sh

      # Sample script execution and GitHub release creation
      - name: videos
        run: |
          cd test
          bash foo.sh  # Make sure foo.sh exists in the 'test' directory and is executable
          gh release create "${{ github.run_number }}.0.0" vid/*.jpg
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
        shell: bash


