name: Build YouTube Video Downloader

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  Download-vid:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install ffmpeg
      - name: Install ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - run: |
          bash foo.sh  # Make sure foo.sh exists in the 'test' directory and is executable
          gh release create "${{ github.run_number }}.0.0" vid/*.mp4

        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
        shell: bash
