name: Build youtube video downloader
on:
  push:
    branches: dl
jobs:
  Download-vid:
    runs-on: ubuntu-latest
    outputs:
      vidTitle: ${{ steps.set_var.outputs.txt }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: chmod +x YoutubeVideoDownloader.sh
    - run: |
        ./YoutubeVideoDownloader.sh
        ls -a
        gh release create  v0.0.${{ github.run_number }} vid.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
      name: videos
