name: Build youtube video downloader
on:
  push:
    branches: dl
jobs:
  Download-vid:
    runs-on: ubuntu-latest
    outputs:
      vidTitle: ${{ steps.set_var.outputs.txt }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install ffmpeg
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install ffmpeg
    - run: chmod +x YoutubeVideoDownloader.sh
    - run: |
        ./YoutubeVideoDownloader.sh
        ls -a
        zip -r vid.zip vid
        gh release create  ${{ github.run_number }}.0.0 vid.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
      name: videos
