name: Build youtube video downloader
on:
  push:
    branches: dl
jobs:
  Download-vid:
    runs-on: ubuntu-latest
    outputs:
      vidTitle: ${{ steps.set_var.outputs.txt }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install ffmpeg
      uses: AnimMouse/setup-ffmpeg@v1

        #- run: chmod +x YoutubeVideoDownloader.sh
    - run: |
        cd test
      #./YoutubeVideoDownloader.sh
        sh foo.sh
        gh release create ${{ github.run_number }}.0.0 vid/*.jpg
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
      name: videos
